name: R
on:
  workflow_dispatch:
  push:
    paths: .github/workflows/ci.yml
    tags:
      - "*"

jobs:
  export_matrix:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        config:
          - name: TextForge-Linux-${{ github.ref_name }}
            export_preset: "Linux"
            platform: Linux
            needs_wine: false
          - name: TextForge-Windows-${{ github.ref_name }}
            export_preset: "Windows Desktop"
            platform: Windows
            needs_wine: true

    name: ${{ matrix.config.name }}
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Wine
      if: matrix.config.needs_wine
      id: wine
      run: |
        sudo apt update
        sudo apt install -y wine64
        echo "WINE_PATH=$(which wine)" >> $GITHUB_OUTPUT

    - name: Download Godot
      run: |
        wget -q https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_linux.x86_64.zip
        wget -q https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_export_templates.tpz
        unzip -q Godot_v4.5-stable_linux.x86_64.zip
        unzip -q Godot_v4.5-stable_export_templates.tpz
        mkdir -p /home/runner/.local/share/godot/export_templates/4.5.stable/
        cp templates/* /home/runner/.local/share/godot/export_templates/4.5.stable/
        chmod +x Godot_v4.5-stable_linux.x86_64

    - name: Import assets
      continue-on-error: true
      run: |
        mkdir -p /home/runner/work/text-forge/text-forge/text-forge-builds/
        ./Godot_v4.5-stable_linux.x86_64 --headless --import || true
        if [ ${{ matrix.config.export_preset }} = 'Linux' ]; then
          ./Godot_v4.5-stable_linux.x86_64 /home/runner/work/text-forge/text-forge/project.godot --headless --export-debug 'Linux' /home/runner/work/text-forge/text-forge/text-forge-builds/TextForge.x86_64 --verbose || true
        elif [ ${{ matrix.config.export_preset }} = 'Windows Desktop' ]; then
          ./Godot_v4.5-stable_linux.x86_64 /home/runner/work/text-forge/text-forge/project.godot --headless --export-debug 'Windows Desktop' /home/runner/work/text-forge/text-forge/text-forge-builds/TextForge.exe --verbose || true
        fi
        ls /home/runner/work/text-forge/text-forge/text-forge-builds/

    - name: Archive
      run: |
        #cd /home/runner/work/text-forge/text-forge/text-forge-builds
        pwd
        cp -r ../data ./
        cp -r ../action_scripts ./
        cp ../README.md ./
        cp ../CHANGELOG.md ./
        zip -r "../${{ matrix.config.name }}.zip" .
        cd ..
        rm -rf text-forge-builds
        ls -lah
        echo "✓ Archive created successfully"

    - name: Artifact
      uses: actions/upload-artifact@v5
      with:
        name: ${{ matrix.config.name }}
        path: ${{ matrix.config.name }}.zip
        #path: text-forge-builds/${{ matrix.config.name }}.zip

    - name: Release
      uses: ncipollo/release-action@v1.20.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: ${{ github.ref_name }}
        artifacts: ${{ matrix.config.name }}.zip
        #artifacts: text-forge-builds/${{ matrix.config.name }}.zip
        allowUpdates: true
        discussionCategory: General
        generateReleaseNotesPreviousTag: true
        makeLatest: legacy
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
